config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'sessions/destroy', to: 'sessions#destroy'
  get 'globalUser', to: 'sessions#grabUser'
  post 'checkIfFollowingBet', to: 'bets#checkIfFollowing'
  post 'followBet', to: 'bets#followBet'
  post 'unfollowBet', to: 'bets#unfollowBet'
  post 'users/followedBets', to: 'users#followedBets'
  post 'users/following', to: 'users#following'
  post 'users/followers', to: 'users#followers'

  post 'checkIfFollowingUser', to: 'users#checkIfFollowing'
  post 'followUser', to: 'users#followUser'
  post 'unfollowUser', to: 'users#unfollowUser'
  
  post 'contracts/edit', to: 'contracts#edit'
  post 'activate', to: 'account_activations#edit'
  get 'users/new'
  get 'users/show', to: 'users#show'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/users/edit', to: 'users#update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      post :following, :followers, :followedBets
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :bets                
  resources :contracts,           only: [:create, :edit, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footerPlus">
  <small>
  <p>by Lucas Crocker</p>
    based off the Ruby on Rails tutorial by <a href="https://www.michaelhartl.com/">Micheal Hartl</a>
  </small>
  <nav>

</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Bettr", root_path, id:"logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", home_path%></li>
            <li><%= link_to "About", about_path%></li>
            <li><%= link_to "Help", help_path%></li>
            <li><%= link_to "Contact", contact_path%></li>
            <% if logged_in?%>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user%></li>
                  <li><%= link_to "Settings", edit_user_path(current_user)%></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to "Log in", login_path%></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<%
=begin%>
 <!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%message_type%>"><%= message %></div>
    <%end%>
    <%= javascript_pack_tag 'hello_vue' %> 
      <%= yield %>


    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html> 
<%
=end%>
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVuejsss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--Google Font-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'main' %>
  </head>

  <body>
    <%
=begin%>
 <%= yield %> 
<%
=end%>
  </body>
</html>